source 'https://rubygems.org'

gem 'awestruct', '~> 0.5.1'
gem 'tilt', '~> 1.3.6', :require => ['asciidoctor']
gem 'redcarpet', '~> 2.3.0'
gem 'slim', '~> 2.0.0'
gem 'less', '~> 2.3.1'
gem 'therubyracer', '~> 0.11.4'
gem 'rb-inotify', '~> 0.9.0'
gem 'puma', '~> 3.12.3' # for a leaner deve server
gem 'guard-livereload'
gem 'yajl-ruby'
gem 'coffee-script'
gem 'htmlcompressor'
gem 'uglifier'
gem 'asciidoctor', '~> 0.1.2'